dist: bionic
language: cpp

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps

addons:
  apt:
    packages:
      - g++-8
      - clang-8

install:
# Download and install recent cmake
    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
        CMAKE_URL="http://www.cmake.org/files/v3.16/cmake-3.16.3-Linux-x86_64.tar.gz"
        mkdir -p ${DEPS_DIR}/cmake
        travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      fi
script:
  - clang++ -std=c++2a -fmodules-ts --precompile math.cppm -o math.pcm
  - clang++ -std=c++2a -fmodules-ts -c math.pcm -o math.o
  - clang++ -std=c++2a -fmodules-ts -c math.cpp -fmodule-file=math.pcm -o math.o
  - clang++ -std=c++2a -fmodules-ts -c main.cpp -fmodule-file=math.pcm -o main.o
  - clang++  math.pcm main.o math.o -o math



